In [1]:
import dash
import dash_bootstrap_components as dbc
import dash_leaflet as dl
import dash_bootstrap_components as dbc 
from dash import Dash, html, Output, Input, State, no_update,dcc
from dash_extensions.enrich import DashProxy, Input, Output, html
from dash_extensions.javascript import assign
from dash_extensions.javascript import arrow_function

import geopandas as gpd
import pandas as pd

In [21]:
df = gpd.read_file("assets/Pozos.geojson")
df = pd.DataFrame(df.drop(columns="geometry"))
print(df.head())

  CVEGEO_LOC     AÑO  NOM_MUN                 NOM_LOC  \
0  130010001  2014.0  Acatlán                 Acatlán
1  130010001  2015.0  Acatlán                 Acatlán
2  130010017  2016.0  Acatlán              Mixquiapan
3  130010020  2013.0  Acatlán  San Bartolo (El Llano)
4  130010021  2013.0  Acatlán            San Dionisio

  Fuente de abastecimiento Coliformes Totales (Ausencia o Presencia/100mL)  \
0         Pozo El Veladero                                       Presencia
1         Pozo Los Fresnos                                       Presencia
2     Manantial Mixquiapan                                       Presencia
3       Manantial Chivería                                       Presencia
4    Manantial Zacacuautla                                       Presencia

  E. Coli (Ausencia o Presencia/100mL) Arsenico (mg/L) Bario (mg/L)  \
0                             Ausencia               0            0
1                             Ausencia               0            0
2                             Ausencia               0            0
3                             Ausencia               0            0
4                             Ausencia               0            0

  Cadmio (mg/L)  ... Fluoruros (mg/L) Nitratos (mg/L) Nitritos (mg/L)     Ph  \
0          None  ...             1.28             1.1           0.003   7.54
1          None  ...                0             0.4           0.003   6.32
2            ND  ...              0.3               0               0  45755
3          None  ...             0.61             0.2          0.0145   7.01
4          None  ...              0.7             0.1           0.013    7.1

  SDT (mg/L) Sulfatos (mg/L) Cloro Total (mg/L) Conductividad (muS/cm)  \
0        456               7                  0                    296
1        345               0                  0                    632
2      45758               0                  0                   41.2
3      172.2              16                  0                    357
4      156.7              10                  0                  360.1

  Temperatura (°C)                                                 ID
0             27.3                   Acatlán_Acatlán_Pozo El Veladero
1             24.7                   Acatlán_Acatlán_Pozo Los Fresnos
2            45763            Acatlán_Mixquiapan_Manantial Mixquiapan
3             27.5  Acatlán_San Bartolo (El Llano)_Manantial Chivería
4             24.3         Acatlán_San Dionisio_Manantial Zacacuautla

[5 rows x 29 columns]

In [31]:
df_filtro = df[df['ID'] == 'San Salvador_Pacheco de Allende_Pozo Pacheco']
df_filtro = df_filtro.drop(columns=['CVEGEO_LOC', 'ID', 'NOM_MUN', 'NOM_LOC', 'Fuente de abastecimiento'])
df_filtro = df_filtro.transpose()

In [32]:
df_filtro.columns = df_filtro.iloc[0]
df_filtro = df_filtro.iloc[1:]

In [33]:
df_filtro

AÑO,2017.0,2016.0,2020.0,2015.0,2015.0
Coliformes Totales (Ausencia o Presencia/100mL),Presencia,Presencia,ND,Presencia,Presencia
E. Coli (Ausencia o Presencia/100mL),Presencia,Ausencia,ND,Ausencia,Ausencia
Arsenico (mg/L),0,0,0,0,0
Bario (mg/L),0,0,0,0,0
Cadmio (mg/L),None,ND,0,None,None
Cobre (mg/L),0.34,0.01,0.26,0.07,0.01
Hierro (mg/L),0.016,0,6.9,0.01,0
Manganeso (mg/L),0,0,0.1,0,0.1
Plomo (mg/L),0,0,0,0,0
Zinc (mg/L),0.035,0.12,0,0.08,0.09
Cianuros (mg/L),0.004,2,0.001,0,0.002
Cloro Residual (mg/L),0.04,0.19,0,0.49,0.13
Cloruros (mg/L),77.5,60.3,127.9,100.4,97.8
Dureza Total (mg/L),159.99,399.99,148.88,375.55,404.44
Fluoruros (mg/L),0.91,1.24,0.68,0.85,0.84
Nitratos (mg/L),1.9,45780,1.8,1.4,1.3
Nitritos (mg/L),0.004,5,0,0.04,0.008
Ph,7.79,7.17,6.9,6.92,7
SDT (mg/L),241,721,70.71,821,801
Sulfatos (mg/L),15,97,99,0,102
Cloro Total (mg/L),0,0.03,0,0.3,0
Conductividad (muS/cm),None,1548,1639,1648,1609
Temperatura (°C),None,45836,28.5,28.1,26.9

In [26]:
columnDefs=[{"field": i} for i in df_filtro.columns]

In [27]:
columnDefs

[{'field': 671},
 {'field': 672},
 {'field': 673},
 {'field': 674},
 {'field': 675}]

In [38]:
import geopandas as gpd
import pandas as pd



df = gpd.read_file("assets/Pozos.geojson")
df = pd.DataFrame(df.drop(columns="geometry"))

df_filtro = df[df['ID'] == 'San Salvador_Pacheco de Allende_Pozo Pacheco']
df_filtro = df_filtro.drop(columns=['CVEGEO_LOC', 'ID', 'NOM_MUN', 'NOM_LOC', 'Fuente de abastecimiento'])

##df_filtro.columns = df_filtro.iloc[0]
##df_filtro = df_filtro.iloc[1:]

In [39]:
df_filtro = df_filtro.T.reset_index()
df_filtro.columns = df_filtro.iloc[0]
df_filtro = df_filtro.iloc[1:]
df_filtro.columns = df_filtro.columns.astype(str)
df_filtro = df_filtro.astype(str)

In [40]:
df_filtro

,AÑO,2017.0,2016.0,2020.0,2015.0,2015.0
1,Coliformes Totales (Ausencia o Presencia/100mL),Presencia,Presencia,ND,Presencia,Presencia
2,E. Coli (Ausencia o Presencia/100mL),Presencia,Ausencia,ND,Ausencia,Ausencia
3,Arsenico (mg/L),0,0,0,0,0
4,Bario (mg/L),0,0,0,0,0
5,Cadmio (mg/L),None,ND,0,None,None
6,Cobre (mg/L),0.34,0.01,0.26,0.07,0.01
7,Hierro (mg/L),0.016,0,6.9,0.01,0
8,Manganeso (mg/L),0,0,0.1,0,0.1
9,Plomo (mg/L),0,0,0,0,0
10,Zinc (mg/L),0.035,0.12,0,0.08,0.09
11,Cianuros (mg/L),0.004,2,0.001,0,0.002
12,Cloro Residual (mg/L),0.04,0.19,0,0.49,0.13
13,Cloruros (mg/L),77.5,60.3,127.9,100.4,97.8
14,Dureza Total (mg/L),159.99,399.99,148.88,375.55,404.44
15,Fluoruros (mg/L),0.91,1.24,0.68,0.85,0.84
16,Nitratos (mg/L),1.9,45780,1.8,1.4,1.3
17,Nitritos (mg/L),0.004,5,0,0.04,0.008
18,Ph,7.79,7.17,6.9,6.92,7
19,SDT (mg/L),241,721,70.71,821,801
20,Sulfatos (mg/L),15,97,99,0,102
21,Cloro Total (mg/L),0,0.03,0,0.3,0
22,Conductividad (muS/cm),None,1548,1639,1648,1609
23,Temperatura (°C),None,45836,28.5,28.1,26.9

In [28]:
def prevent_duplicates(cols):
    seen = {}
    new_cols = []
    for col in cols:
        if col in seen:
            seen[col] += 1
            new_cols.append(f"{col}.{seen[col]}")
        else:
            seen[col] = 0
            new_cols.append(col)
    return new_cols

df_filtro.columns = prevent_duplicates(df_filtro.columns)

In [29]:
df_filtro

,AÑO,2017.0,2016.0,2020.0,2015.0,2015.0.1
1,Coliformes Totales (Ausencia o Presencia/100mL),Presencia,Presencia,ND,Presencia,Presencia
2,E. Coli (Ausencia o Presencia/100mL),Presencia,Ausencia,ND,Ausencia,Ausencia
3,Arsenico (mg/L),0,0,0,0,0
4,Bario (mg/L),0,0,0,0,0
5,Cadmio (mg/L),None,ND,0,None,None
6,Cobre (mg/L),0.34,0.01,0.26,0.07,0.01
7,Hierro (mg/L),0.016,0,6.9,0.01,0
8,Manganeso (mg/L),0,0,0.1,0,0.1
9,Plomo (mg/L),0,0,0,0,0
10,Zinc (mg/L),0.035,0.12,0,0.08,0.09
11,Cianuros (mg/L),0.004,2,0.001,0,0.002
12,Cloro Residual (mg/L),0.04,0.19,0,0.49,0.13
13,Cloruros (mg/L),77.5,60.3,127.9,100.4,97.8
14,Dureza Total (mg/L),159.99,399.99,148.88,375.55,404.44
15,Fluoruros (mg/L),0.91,1.24,0.68,0.85,0.84
16,Nitratos (mg/L),1.9,45780,1.8,1.4,1.3
17,Nitritos (mg/L),0.004,5,0,0.04,0.008
18,Ph,7.79,7.17,6.9,6.92,7
19,SDT (mg/L),241,721,70.71,821,801
20,Sulfatos (mg/L),15,97,99,0,102
21,Cloro Total (mg/L),0,0.03,0,0.3,0
22,Conductividad (muS/cm),None,1548,1639,1648,1609
23,Temperatura (°C),None,45836,28.5,28.1,26.9

In [31]:
df = gpd.read_file("assets/Pozos.geojson")
df = pd.DataFrame(df.drop(columns="geometry"))

df_filtro = df[df['ID'] == 'San Salvador_Pacheco de Allende_Pozo Pacheco']
df_filtro = df_filtro.drop(columns=['CVEGEO_LOC', 'ID', 'NOM_MUN', 'NOM_LOC', 'Fuente de abastecimiento'])

columnas = df_filtro.columns.values[1:]

In [33]:
df_filtro

,AÑO,Coliformes Totales (Ausencia o Presencia/100mL),E. Coli (Ausencia o Presencia/100mL),Arsenico (mg/L),Bario (mg/L),Cadmio (mg/L),Cobre (mg/L),Hierro (mg/L),Manganeso (mg/L),Plomo (mg/L),...,Dureza Total (mg/L),Fluoruros (mg/L),Nitratos (mg/L),Nitritos (mg/L),Ph,SDT (mg/L),Sulfatos (mg/L),Cloro Total (mg/L),Conductividad (muS/cm),Temperatura (°C)
671,2017.0,Presencia,Presencia,0,0,None,0.34,0.016,0,0,...,159.99,0.91,1.9,0.004,7.79,241,15,0,None,None
672,2016.0,Presencia,Ausencia,0,0,ND,0.01,0,0,0,...,399.99,1.24,45780,5,7.17,721,97,0.03,1548,45836
673,2020.0,ND,ND,0,0,0,0.26,6.9,0.1,0,...,148.88,0.68,1.8,0,6.9,70.71,99,0,1639,28.5
674,2015.0,Presencia,Ausencia,0,0,None,0.07,0.01,0,0,...,375.55,0.85,1.4,0.04,6.92,821,0,0.3,1648,28.1
675,2015.0,Presencia,Ausencia,0,0,None,0.01,0,0.1,0,...,404.44,0.84,1.3,0.008,7,801,102,0,1609,26.9

In [32]:
columnas

array(['Coliformes Totales (Ausencia o Presencia/100mL)',
       'E. Coli (Ausencia o Presencia/100mL)', 'Arsenico (mg/L)',
       'Bario (mg/L)', 'Cadmio (mg/L)', 'Cobre (mg/L)', 'Hierro (mg/L)',
       'Manganeso (mg/L)', 'Plomo (mg/L)', 'Zinc (mg/L)',
       'Cianuros (mg/L)', 'Cloro Residual (mg/L)', 'Cloruros (mg/L)',
       'Dureza Total (mg/L)', 'Fluoruros (mg/L)', 'Nitratos (mg/L)',
       'Nitritos (mg/L)', 'Ph', 'SDT (mg/L)', 'Sulfatos (mg/L)',
       'Cloro Total (mg/L)', 'Conductividad (muS/cm)', 'Temperatura (°C)'],
      dtype=object)

TypeError: agg function failed [how->mean,dtype->object]